apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Demo01
  description: Backstage Demo to Display Github Repo
  annotations:
    github.com/project-slug: Sandy1101/Demo01
  links:
    - title: Website
      url: http://backstage.io
spec:
  type: other
  lifecycle: development
  owner: guests
