apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: demo-template
  title: Create Repo
  description: Sample Template and publish it to GitHub
  tags:
    - template
spec:
  owner: team-a
  type: service
  parameters:
    - title: Create a new Webm app
      required:
        - name
      properties:
        name:
          title: Name of the App
          type: string
          description: Name for the new app repository
        description:
          title: App Description
          type: string
          description: Description for the app
        visibility:
          title: Repository Visibility
          type: string
          enum:
            - private
            - public
          default: public
  steps:
    - id: fetch
      name: Fetch Template
      action: fetch:template
      input:
        url: https://github.com/Sandy1101/Demo01
        branch: main
        targetPath: .
    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        repoUrl: https://github.com/Sandy1101/${{ parameters.name }}
        description: ${{ parameters.description }}
        visibility: ${{ parameters.visibility }}
    - id: register
      name: Register Component in Backstage
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Backstage Component
        url: /catalog/default/component/${{ parameters.name }}
